### ISSUE TITLE
ClearML - allow multiple levels to subfolders under a project

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#107]
Organizing experiments under a project (e.g., 'BT-English') is convenient for keeping experiments reasonably organized.  However, there are frequently multiple avenues of investigation going under a single project.  It would be helpful to allow subfolders to be created under a project (e.g., 'BT-English > aligners'), with a number of experiments in each subfolder.  Currently, the logic for launching an experiment doesn't account for subfolders.

Ideally, it should be possible to have several levels of subfolders under a project in order to keep experiments well organized.

**Comment by johnml1135** [comment]
Currently a workaround:
* Create a single folder called "BT-English_aligners

Proposal:
* ClearML experiments can be nested.
* For a path of:
  * name_1/name_1/name_3/name_4
* It would create:
  * <project = name_1>/<nested project = name_2>/<nested nested project = name_3>/<experiment = name_4>

This should be straightforward and has been supported by ClearML since 1.0:
* ClearML Server 1.0.0# Features
  * Add Multi-level project hierarchy - Projects can now contain sub-projects
* https://clear.ml/docs/latest/docs/release_notes/ver_1_0/
Is this what you want?

**Comment by mmartin9684-sil** [comment]
That proposal should work.

Do we need to be careful with experiment name collisions?  It doesn't seem so, but I haven't watched closely.  For instance, this shouldn't create a problem for ClearML:

- name_1/name_2/name_3/name_4, and
- name_1/name_2/name_5/name_4

There would be two 'name_4' experiments with that setup.  I think that is OK, right?
