### ISSUE TITLE
Retain ZWJ/ZWNJ for NLLB models

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#164]
The NLLB tokenizer normalizes the zero width joiner (ZWJ) / non-joiner (ZWNJ) characters to spaces before tokenizing the text.  If the target language text includes these characters, this normalization means that the fine-tuned models do not learn to generate ZWJ/ZWNJ characters in the predictions.

**Comment by ddaspit** [comment]
In order to update the NLLB sentencepiece model to support ZWJ/ZWNJ, we will need to do two things:
1. Update the precompiled character mapping rules to not map ZWJ and ZWNJ to spaces.
2. Insert the ZWJ and ZWNJ characters as pieces in the model.

How we go about doing this will depend on which HF tokenizer we are going to use. HF has two types of tokenizers: slow and fast. Slow uses the sentencepiece library and a sentencepiece model file. Fast uses the HF Tokenizers library and a tokenizer.json file. In silnlp and Serval, we have been using the fast tokenizer. The sentencepiece model file is stored in the protobuf format, a binary serialization format. The sentencepiece model is speced in [this proto file](https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto). The tokenizer.json file is a bit easier to update, since it is json. The character mapping rules are precompiled into a binary format. We should be able to extract the precompiled rules from a setnencepiece model file that we trained for an OpenNMT model.

**Comment by ddaspit** [comment]
One possible way to do this is to update the sentencepiece model file and then convert from a slow tokenizer to a fast tokenizer. HF provides a [function](https://github.com/huggingface/transformers/blob/fabe17a726bbf6081cfbcc975d8ac451a81f3e2d/src/transformers/convert_slow_tokenizer.py#LL1282C8-L1282C8) for doing this.

**Comment by ddaspit** [comment]
@mshannon-sil Here is a NLLB sentencepiece model file that has been updated with the necessary changes.
[sil-nllb.zip](https://github.com/sillsdev/silnlp/files/11624136/sil-nllb.zip)

**Comment by ddaspit** [comment]
Here is a modified version of the NLLB `tokenizer.json` file that includes support for ZWJ/ZWNJ characters.
[tokenizer.zip](https://github.com/sillsdev/silnlp/files/11662736/tokenizer.zip)

**Comment by ddaspit** [comment]
Here is a modified version of the NLLB tokenizer.json file that includes support for ZWJ/ZWNJ characters.
[nllb-tokenizer-zwj-zwnj.zip](https://github.com/sillsdev/silnlp/files/11663036/nllb-tokenizer-zwj-zwnj.zip)
