### ISSUE TITLE
updated Bleu score - remove tokenizing or reference text

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#193]
Only normalize reference coprora - don't tokenize/detokenize.

**Comment by mshannon-sil** [comment]
@ddaspit So it turns out that it's already only normalizing corpora. It doesn't do any tokenization/detokenization for `test.trg.detok.txt`, despite what the name might imply. I'm looking into the documentation to see if I can tweak how normalization is done so that it doesn't just replace unknown characters with empty space.

**Comment by mshannon-sil** [comment]
Nevermind, normalize_all() likely ends up calling tokenize and detokenize inside of it since the normalize() definition does, although it's not showing up when stepping through the code.
