### ISSUE TITLE
Load HF model using torch.float16

### ISSUE THREAD

**Issue by ddaspit** [sillsdev/silnlp#292]
We fine tune HF models using mixed precision (`fp16`). In spite of this, I believe that models like NLLB are still loaded using `torch.float32` weights. We should try forcing the model to load using `torch.float16` to see if it reduces memory usage and increases inferencing speed. The `dtype` can be [specified](https://huggingface.co/docs/transformers/main_classes/model#model-instantiation-dtype) when the model is loaded.

**Comment by isaac091** [comment]
I'm getting an error when I try to do this: `ValueError: Attempting to unscale FP16 gradients.`. From what I've been reading, you can't train a model loaded with `torch_dtype=torch.float16` because the optimization step still requires `float32`s, and just using mixed precision is supposed to take care of everything, so I'm not sure this is something we can do.

**Comment by ddaspit** [comment]
When are you loading the model using `torch_dtype=torch.float16`? Before training or inferencing? Try using it only before inferencing.
