### ISSUE TITLE
NLLB mismatch for Modern Standard Arabic training data and spellings in religious texts (e.g., ONAV)

### ISSUE THREAD

**Issue by mmartin9684-sil** [sillsdev/silnlp#298]
The NLLB model appears to have been trained with Modern Standard Arabic (MSA; _arb_) training data that is typical for common use, but not for religious texts (e.g., Biblica's Open New Arabic Version (ONAV)).  When the fully vocalized spellings used in religious texts are tokenized, they are generally tokenized character-by-character, with few multi-character tokens.  This creates a much more challenging MT scenario.

In order to use a translation like the Biblica ONAV as a source text for training and drafting, the text will need to be "normalized" from the fully vocalized spellings to more commonly used spellings (see, e.g., [cltk.org](url)).

**Comment by Enkidu93** [comment]
How much of a priority is this? And who is doing what? I'm happy to try normalizing the ONAV text with cltk or a similar library and run a model for comparison.

**Comment by mshannon-sil** [comment]
@Enkidu93 since you're already familiar with cltk, that would be great if you could run a simple script to see what output you get when normalizing the ONAV text with cltk. If that works well, I can take care of integrating it with SILNLP.

**Comment by Enkidu93** [comment]
> @Enkidu93 since you're already familiar with cltk, that would be great if you could run a simple script to see what output you get when normalizing the ONAV text with cltk. If that works well, I can take care of integrating it with SILNLP.

Yep, can do. I already have cltk installed etc. Would you like to run a model for comparison as well or would you like me to do that? Or do you think that's not worth doing?

**Comment by Enkidu93** [comment]
Looks like cltk was using pyarabic under the hood. I ran code like this locally: 
```
from pyarabic.araby import reduce_tashkeel, strip_tashkeel
text = ""
with open('some/path/test.src.detok.txt', 'r') as f:
    text = f.read()

text = reduce_tashkeel(text)
with open('some/path/test.src.detok_lessvocalized.txt', 'w') as f:
    f.write(text)

text = strip_tashkeel(text)
with open('/some/path/test.src.detok_unvocalized.txt', 'w') as f:
    f.write(text)
```
Looks like stripping all tashkil leaves us with a source that's most like what NLLB was trained on. However, the Hejazi, for example, has some tashkil, and the reduced tashkil (i.e., bascially only including tashkil where it could be ambiguous) looks more similar to what the Hejazi has in terms of level of vocalization. I imagine `strip_tashkeel` will give you the best results, but it may be worth running a `reduce_tashkeel` as well. You can install pyarabic with, as you'd expect, `pip install pyarabic`. Let me know if I can do anything else.

**Comment by mshannon-sil** [comment]
This is awesome, thank you so much! I'll take a look at testing this with some SILNLP experiments this afternoon to see how it affects the BLEU score.

**Comment by ddaspit** [comment]
Excellent work. I like to see everybody collaborating to solve these kinds of issues. It is this kind of detailed work that makes SF/Serval such a unique contribution to the Biblical NLP community.

**Comment by Enkidu93** [comment]
I've run three tests surrounding the original problem project - same target in each (an Arabic dialect); one with the unedited ONAV, one with ONAV with reduced tashkil, and one with no tashkil. The fewer tashkil, the better the sources aligned with the target and the 'better' tokenized the source was (larger, more meaningful tokens rather than individual letters). Strangely, the no-tashkil model has the lowest BLEU score. The reduced-tashkil had a slightly worse BLEU score, but seems generally fairly comparable across metrics and looking at select verses manually. I investigated the differences between the predictions that contributed most the differences in BLEU score and noticed that frequently the situation was this: The translators in the target had inconsistently (as in they had left them out of a phrase) used tashkil, and the no-tashkil had actually included appropriate tashkil in that word whereas the reference had none. In a couple cases, the no-tashkil had the correct word when the other two did not, but because of the tashkil, the metrics evaluated the no-tashkil translation more poorly. In light of that, I'm going to try translating into a majority language, and see what the performance is there. If the no-tashkil outperforms the rest (as I suspect it might), it may be worth stripping tashkil as a default even if that's not positively reflected in the BLEU score outcomes of the original project.

**Comment by ddaspit** [comment]
Let me make sure I understand this correctly. There are tashkil in the target translation, but we aren't stripping them out. Is that correct? The model that includes tashkil in the ONAV does a better job of inserting the tashkil in the target translation, which results in a higher BLEU score. Is that correct?

**Comment by Enkidu93** [comment]
Yes, there are tashkil in both. No stripping them from the target. Basically, yes. For whatever reason, the model with an untouched text seems to be better at including tashkil in a way that's consistent with the inconsistent use of tashkil in the target.

**Comment by ddaspit** [comment]
By stripping out tashkil on the source-side, we are probably removing information that helps the model to determine when to insert them on the target-side. If we strip tashkil from the target translation, it will remove that variable from the experiment.

**Comment by Enkidu93** [comment]
Yes, I considered that. Maybe I'll give that a try as well. I don't know that that would be tenable, of course, in practice since we wouldn't have a way of restoring the tashkil as needed (although it could simplify the problem significantly if we could). I do wonder - given that the translation seems to be inconsistent itself - if it would be worth interfacing with teams to see if some kind of normalization on the target side might be amenable on a case-by-case basis if this is a persistent issue.

**Comment by ddaspit** [comment]
My suggestion is really on feasible for testing purposes. It would be a more "realistic" test than German, but the German test essentially accomplishes the same thing, so it is probably sufficient.

**Comment by Enkidu93** [comment]
Is there anything actionable here? Should we close this issue? Should we add support for reduced/stripped tashkil and so it's there if needed? Or because there was no definite benefit, should we just skip it?

**Comment by ddaspit** [comment]
We can close it without any further action.

**Comment by mshannon-sil** [comment]
Besides normalizing the text, Bethany, Michael, and I discussed that we could experiment with adding new tokens to the tokenizer and seeing if that would help create larger tokens that might offset the impact of vocalizations. Should we leave this issue open until we get results from that?

**Comment by Enkidu93** [comment]
I don't know if this covers what you had in mind, but as part of the TokenizerVocabSize tests, ONAV as source was tested for one project pair, and the characters-only addition as well as the vocab sizes tested there seemed to not make any significant difference (although it's just the one data point). There was a slight boost which was comparable to the difference seen with the reduced tashkil source: i.e., <= 0.5 BLEU point.

**Comment by mshannon-sil** [comment]
So I took a look, and in those experiments ONAV was the source, but only the target was being used to update the tokenizer. So we should run those same experiments again updating the source instead of the target this time.

**Comment by Enkidu93** [comment]
You're totally right.

**Comment by mshannon-sil** [comment]
I ran some experiments with updating the tokenizer using ONAV. There weren't any configurations that resulted in more than a negligible increase in BLEU score. Since the baseline (no tokenizer updates) BLEU score was already nearly 40 in the set of experiments I ran, I don't think any further investigations need to be conducted at this time.
