### ISSUE TITLE
12 Terrabytes of Experiments - clean it up

### ISSUE THREAD

**Issue by johnml1135** [sillsdev/silnlp#355]
Can we keep the experiment files and delete the models?  Therefore every experiment would only be a few MB rather than a few GB and we can bring down the experiment size from 12 TB to < 100 GB.
Can we write a script to walk through all the S3 bucket folders to delete all models that are over 3 months old?

**Comment by davidbaines** [comment]
There are models that I would occasionally use that are more than three months old.  Sometimes I might be asked to use a model that's more than a year old.  Those are fairly rare though so most certainly could be deleted.  I wonder how much all that storage costs, it would be good to have an idea so that we can weigh that up against the cost of retraining models.
