### ISSUE TITLE
Check whether data is being tokenized before calculating tokenization stats

### ISSUE THREAD

**Issue by mshannon-sil** [sillsdev/silnlp#365]
Currently, tokenization_stats.csv/xlsx are being generated even for configs that specify `tokenize: false`. The tokenization_stats.csv/xlsx should not be generated in this scenario.

**Comment by AmeWenJ** [comment]
Hi, it seems I cannot reproduce this issue. I never had the tokenization_stats.csv/xlsx file in my previous experiments. Besides, I found out an old experiment with that file in the folder and copied the config file to run it again, but it still didn't show up after the task was done.

**Comment by mshannon-sil** [comment]
@AmeWenJ You'll need to run experiment.py with the `--stats` flag in order for the tokenization_stats.csv and tokenization_stats.xlsx files to appear.

**Comment by AmeWenJ** [comment]
@mshannon-sil Thank you for pointing it out! I'll look into it with the flag on.

**Comment by AmeWenJ** [comment]
@mshannon-sil From what I've observed, before sending the tokenizer to actually build the corpora (the last step of the preprocess), the code will always load a pretrained tokenizer first (which is also how the class is defined, i.e. the method is supposed to output a pretrained tokenizer). However, the tokenizer being used in building corpora is always the NullTokenizer instead of the pretrained one. 

An easy way to solve this is to just avoid generating files if the data["tokenize"] = False. I don't know if we should deal with the pretrained tokenizer (which is stored in the field _tokenizer in HuggingFaceConfig). It is an optional field and has to be a PretrainedTokenizer, so we may be able to set it to None and not load anything in this case. I'm not sure if this will influence any other function yet. 

Would you like to share some suggestions? Do we just go for the easy solution first?

**Comment by mshannon-sil** [comment]
I think the most straightforward approach works fine for this issue, which like you said is just to avoid generating the files if `data["tokenize"] = False`. One point to clear up is that the tokenizer being loaded right before `self._build_corpora` shouldn't be `NullTokenizer`. I tested to make sure, and I'm getting a `NllbTokenizerFast` type, which matches my expectation.

**Comment by AmeWenJ** [comment]
I printed the tokenizer that is fed to self._build_corpora (in config.py) as a parameter, and it is <silnlp.nmt.tokenizer.NullTokenizer object at 0x7f85dc177f40>

I also used the debug mode to check the type, and it shows that the tokenizer inside the method is also this type. However, the self._tokenizer (in hugging_face_config.py) is indeed NllbTokenizerFast type. I checked this at the end of the _build_vocabs (in hugging_face_config.py) method. 

The create_tokenizer (in hugging_face_config.py) method outputs the NullTokenizer if self.data["tokenize"] = False, which is the direct assignment to the tokenizer that gets fed into self._build_corpora (in config.py).


I highlighted the file because all these methods may be confusing together. Would you please try testing it again and let me know if my approach was incorrect?

**Comment by mshannon-sil** [comment]
We had a discussion and determined that it's a `NullTokenizer` specifically when the config includes `tokenize: false`. We also discussed that we may want to skip the `_build_vocabs` method if tokenization isn't happening, since the entire method is related to tokenization.

**Comment by AmeWenJ** [comment]
I tested with skipping the `_build_vocabs` method when the config includes `tokenize: false`, and it still could run and complete the task. Shall I commit the changes and push now?

**Comment by mshannon-sil** [comment]
Yes, you can go ahead and push and submit a pull request when you're ready.
